AdrianJSClark/aydsko-iracingdata

- src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs
- src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonResultsHandlesBadRequestAsync/0.json
- src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonResultsHandlesBadRequestAsync/1.json
- src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonResultsSuccessfulAsync/0.json
- src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonResultsSuccessfulAsync/1.json
- src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonResultsSuccessfulAsync/2.json
- src/Aydsko.iRacingData/IRacingDataClient.cs
- src/Aydsko.iRacingData/Results/EventType.cs
- src/Aydsko.iRacingData/Results/SeasonResults.cs
Implement the "results/season_results" endpoint which allows you to retrieve the races run in a particular series' week of a particular season of competition.
Fixes #3
> Implement "results/season_results" Endpoint

- src/Aydsko.iRacingData.UnitTests/Converters/JsonConverterTestExtensions.cs
- src/Aydsko.iRacingData.UnitTests/Converters/TenThousandthSecondDurationConverterTests.cs
- src/Aydsko.iRacingData/Converters/TenThousandthSecondDurationConverter.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
- src/Aydsko.iRacingData/Results/Result.cs
- src/Aydsko.iRacingData/Results/SeasonRaceResult.cs
- src/Aydsko.iRacingData/Results/SeasonResultTrack.cs
- src/Aydsko.iRacingData/Results/SeasonResults.cs
- src/Aydsko.iRacingData/Results/SubsessionChartLap.cs
- src/Aydsko.iRacingData/Results/SubsessionLap.cs
- src/Aydsko.iRacingData/Results/SubsessionLapHeader.cs
- src/Aydsko.iRacingData/Stats/Race.cs
- src/Aydsko.iRacingData/Stats/SeasonTimeTrialResult.cs
- src/Aydsko.iRacingData/Tracks/Track.cs
The raw iRacing API results use a number type which carries duration values to the ten-thousandth of a second. So, for example, a lap which was displayed in the iRacing results page as 1:23.456 would be returned as 834560.
This change implements a converter for that and applies this "TenThousandthSecondDurationConverter" to all duration-like fields using the  so the values can be expressed as "TimeSpan" instead of just a "long" value.
Fixes: #47
> Add JSON Converter for iRacing Durations & Use As Appropriate

- src/Aydsko.iRacingData/Cars/CarInfo.cs
- src/Aydsko.iRacingData/Common/DataResponse.cs
- src/Aydsko.iRacingData/Leagues/League.cs
- src/Aydsko.iRacingData/Leagues/RosterMember.cs
- src/Aydsko.iRacingData/Member/DriverInfo.cs
- src/Aydsko.iRacingData/Member/MemberInfo.cs
- src/Aydsko.iRacingData/Results/Result.cs
- src/Aydsko.iRacingData/Results/SeasonRaceResult.cs
- src/Aydsko.iRacingData/Results/SessionInfo.cs
- src/Aydsko.iRacingData/Results/SubSessionResult.cs
- src/Aydsko.iRacingData/Series/Weather.cs
- src/Aydsko.iRacingData/Stats/Race.cs
- src/Aydsko.iRacingData/Stats/SeasonDriverStandingsHeader.cs
- src/Aydsko.iRacingData/Stats/SeasonQualifyResultsHeader.cs
- src/Aydsko.iRacingData/Stats/SeasonTeamStandingsHeader.cs
- src/Aydsko.iRacingData/Stats/SeasonTimeTrialResultsHeader.cs
- src/Aydsko.iRacingData/Stats/SeasonTimeTrialStandingsHeader.cs
- src/Aydsko.iRacingData/Tracks/Track.cs
The correct .NET data type for a value which is considered an instant is
"DateTimeOffset". Ensure that these are used as appropriate.
Fixes: #51
> Use "DateTimeOffset" for Instant Values

- src/Aydsko.iRacingData/Package Release Notes.txt
- src/Aydsko.iRacingData/Results/SeasonRaceResult.cs
- src/Aydsko.iRacingData/Results/SeasonResults.cs
- src/Aydsko.iRacingData/Results/SubSessionResult.cs
- src/Aydsko.iRacingData/Series/RaceWeeks.cs
- src/Aydsko.iRacingData/Series/Schedule.cs
- src/Aydsko.iRacingData/Stats/SeasonDriverStandingsHeader.cs
- src/Aydsko.iRacingData/Stats/SeasonQualifyResultsHeader.cs
- src/Aydsko.iRacingData/Stats/SeasonTeamStandingsHeader.cs
- src/Aydsko.iRacingData/Stats/SeasonTimeTrialResultsHeader.cs
- src/Aydsko.iRacingData/Stats/SeasonTimeTrialStandingsHeader.cs
The iRacing Data API operates using zero-based race week numbers. For most display or processing purposes people will prefer to work with a one-based count.
This change adds a convenience method which can be used to directly display or work with the actual one-based week number instead of the zero-based "index".
Fixes: #52
> Provide "Race Week Number" Convenience Property

- src/Aydsko.iRacingData/Results/DriverResult.cs
- src/Aydsko.iRacingData/Results/Result.cs
Compared `Result` and `DriverResult`  after finding some unexpected differences.
> Improved naming consistency between Result and DriverResult

- src/Aydsko.iRacingData/Aydsko.iRacingData.csproj
Avoid duplicates due to automatic version number incrementing. These settings should configure PR builds to match the name of the branch. This should avoid issues when a single commit PR build generates the same version number due to a same height.
> Use PR Branch As PreRelease Version

- src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs
- src/Aydsko.iRacingData.UnitTests/Responses/ResponseUnauthorized/0.json
- src/Aydsko.iRacingData.UnitTests/Responses/ResponseUnauthorized/1.json
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/Exceptions/iRacingUnauthorizedResponseException.cs
This will raise a `iRacingUnauthorizedResponseException` instead of the System.Web exception. It will also set `IsLoggedIn` to make the following call try to authenticate itself. Expired sessions will give you unauthorized errors, so if you retry this 2nd call should succeed.
> Improve handling unauthorized responses

- .github/workflows/build.yml
- src/Aydsko.iRacingData.IntegrationTests/Aydsko.iRacingData.IntegrationTests.csproj
- src/Aydsko.iRacingData.IntegrationTests/BaseIntegrationFixture.cs
- src/Aydsko.iRacingData.IntegrationTests/Member/MemberInfoTest.cs
- src/Aydsko.iRacingData.IntegrationTests/Results/ResultsSearchSeriesTest.cs
- src/Aydsko.iRacingData.IntegrationTests/TestLogger.cs
- src/Aydsko.iRacingData.IntegrationTests/Usings.cs
- src/Aydsko.iRacingData.IntegrationTests/appsettings.json
- src/Aydsko.iRacingData.UnitTests/Aydsko.iRacingData.UnitTests.csproj
- src/Aydsko.iRacingData/Aydsko.iRacingData.csproj
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/Extensions.cs
- src/iRacing Data API.sln
The results search call was throwing an exception if there were zero results. Fix this and check it by performing an actual search against the iRacing API using the new integration tests.
> Add Integration Tests & Fix Search Failing on No Results

- src/Aydsko.iRacingData.UnitTests/Responses/GetMemberInfoSucceedsAsync/2.json
- src/Aydsko.iRacingData/Member/Account.cs
Create a failing test for the iRacing Dollars & Credits fields by using decimal values then resolve the issue.
Fixes: #127
> Modify iRacing Dollars & Credits to Accept Decimal

- src/Aydsko.iRacingData.UnitTests/LoginViaOptionsTests.cs
- src/Aydsko.iRacingData/CompatibilitySuppressions.xml
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/IDataClient.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
- src/Aydsko.iRacingData/iRacingDataClientOptions.cs
Give the user of the library an option to supply a pre-encoded password value suitable for passing directly to iRacing's API. This opens the possibility of running the library without the system it operates on ever knowing the plain-text password.
> Accept Pre-Hashed Password

- .github/workflows/_build.yml
- .github/workflows/ci.yml
- .github/workflows/create-release.yml
- .github/workflows/pr.yml
Restructure the builds to be based around the same build script but include it. This means we can do away with mulitple workflows executing for a single action (e.g. one "build" workflow and one "create release" workflow) and instead a single workflow with multiple jobs can be executed for a single task.
This means a continuous integration build is one workflow with build, test report, and deployment of pre-release, instead of two workflows as it was before.
> Rework Builds

- src/Aydsko.iRacingData.IntegrationTests/Tracks/GetTracksTests.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
- src/Aydsko.iRacingData/Tracks/Track.cs
Include documentation about the `Track.TrackConfigLength` and add a `Track.TrackConfigLengthKm` property that converts the initial property value, which is in "miles", to "kilometres".
Fixes: #132
> Document "TrackConfigLength" and Convert to km

- src/Aydsko.iRacingData.UnitTests/Aydsko.iRacingData.UnitTests.csproj
- src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonStandingsAsync/0.json
- src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonStandingsAsync/1.json
- src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonStandingsAsync/2.json
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/IDataClient.cs
- src/Aydsko.iRacingData/Leagues/SeasonStandings.cs
- src/Aydsko.iRacingData/Leagues/SeasonStandingsDriver.cs
- src/Aydsko.iRacingData/Leagues/SeasonStandingsDriverStandings.cs
- src/Aydsko.iRacingData/Leagues/SeasonStandingsStandingsDetails.cs
- src/Aydsko.iRacingData/Leagues/SeasonStandingsTeam.cs
- src/Aydsko.iRacingData/Leagues/SeasonStandingsTeamStandings.cs
The result returns `roster` it according to IRacing devs this field should be there. Also the team standings includes `driver_nickname` which I am also assuming is a mistake.
The two optional params (`car_id` and `car_class_id`) wasn't tested as I don't have any result with multiclass.
> Implements https://members-ng.iracing.com/data/league/season_standings

- src/Aydsko.iRacingData.IntegrationTests/Aydsko.iRacingData.IntegrationTests.csproj
- src/Aydsko.iRacingData.UnitTests/Aydsko.iRacingData.UnitTests.csproj
- src/Aydsko.iRacingData.UnitTests/Converters/JsonConverterTestExtensions.cs
- src/Aydsko.iRacingData.UnitTests/Converters/ServiceStatusHistoryItemConverterTests.cs
- src/Aydsko.iRacingData.UnitTests/Converters/StatusTimeStampConverterTests.cs
- src/Aydsko.iRacingData.UnitTests/Converters/StringFromStringOrNumberConverterTests.cs
- src/Aydsko.iRacingData.UnitTests/Converters/TenThousandthSecondDurationConverterTests.cs
- src/Aydsko.iRacingData.UnitTests/LoginViaOptionsTests.cs
- src/Aydsko.iRacingData.UnitTests/MockedHttpMessageHandler.cs
- src/Aydsko.iRacingData.UnitTests/MockedHttpRequest.cs
- src/Aydsko.iRacingData.UnitTests/ServicesTests.cs
- src/Aydsko.iRacingData/CompatibilitySuppressions.xml
- src/Aydsko.iRacingData/Converters/StatusTimeStampConverter.cs
The unit tests used to run against both `net6.0` and `netcoreapp3.1` where the latter was used to pick up the `netstandard2.0` version of the library.
Now that .NET Core 3.1 has fallen out of support, the only reason to have the `netstandard2.0` target is for .NET Framework compatibility. This means that the unit tests should also execute against .NET Framework. To achieve this, replace the old .NET Core 3.1 target with .NET Framework 4.8 (aka `net48`) to run the `netstandard2.0` target tests.
> Replace "netcoreapp31" With "net48" For Tests 

- src/.editorconfig
- src/Aydsko.iRacingData.IntegrationTests/Aydsko.iRacingData.IntegrationTests.csproj
- src/Aydsko.iRacingData.IntegrationTests/BaseIntegrationFixture.cs
- src/Aydsko.iRacingData.IntegrationTests/CachingIntegrationFixture.cs
- src/Aydsko.iRacingData.IntegrationTests/DataClientIntegrationFixture.cs
- src/Aydsko.iRacingData.IntegrationTests/Lookups/CachingLookupTests.cs
- src/Aydsko.iRacingData.IntegrationTests/Lookups/LookupTests.cs
- src/Aydsko.iRacingData.IntegrationTests/Member/CachingMemberInfoTest.cs
- src/Aydsko.iRacingData.IntegrationTests/Member/MemberInfoTest.cs
- src/Aydsko.iRacingData.IntegrationTests/Results/CachingResultsGetTest.cs
- src/Aydsko.iRacingData.IntegrationTests/Results/CachingResultsSearchSeriesTest.cs
- src/Aydsko.iRacingData.IntegrationTests/Results/ResultsGetTest.cs
- src/Aydsko.iRacingData.IntegrationTests/Results/ResultsSearchSeriesTest.cs
- src/Aydsko.iRacingData.IntegrationTests/TestLogger.cs
- src/Aydsko.iRacingData.IntegrationTests/Tracks/CachingGetTracksTests.cs
- src/Aydsko.iRacingData.IntegrationTests/Tracks/GetTracksTests.cs
- src/Aydsko.iRacingData.UnitTests/ServicesTests.cs
- src/Aydsko.iRacingData.UnitTests/TestLogger.cs
- src/Aydsko.iRacingData/Aydsko.iRacingData.csproj
- src/Aydsko.iRacingData/CachingDataClient.cs
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/LoggingExtensions.cs
- src/Aydsko.iRacingData/ServicesExtensions.cs
Initial implementation of caching to address #165.
Right now you need to ensure you've added the memory cache to the services and then call `AddIRacingDataApiWithCaching` to configure the version of the data client with caching enabled.
> Initial Caching Implementation

- src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs
- src/Aydsko.iRacingData/Aydsko.iRacingData.csproj
- src/Aydsko.iRacingData/CompatibilitySuppressions.xml
- src/Aydsko.iRacingData/Package Release Notes.txt
- src/Aydsko.iRacingData/Results/LapFlags.cs
- src/Aydsko.iRacingData/Results/SubsessionLap.cs
The `SubsessionLap.Flags` value is actually a bitwise enumeration. Implement proper support and move the underlying value to the `FlagsRaw` field.
Fixes #169
> Implement Flags Enum for Lap Events

- reference/doc.json
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/IDataClient.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
- src/Aydsko.iRacingData/Searches/SearchParameters.cs
Include the new "TeamId" parameter for both the hosted and official search endpoints which was introduced with the 2023 Season 3 build.
Fixes: #178
> Add "TeamId" to Hosted and Official Search

- src/Aydsko.iRacingData.IntegrationTests/TestLogger.cs
- src/Aydsko.iRacingData.UnitTests/Converters/JsonConverterTestExtensions.cs
- src/Aydsko.iRacingData.UnitTests/DataClientTrackAssetScreenshotUrisTests.cs
- src/Aydsko.iRacingData.UnitTests/MockedHttpMessageHandler.cs
- src/Aydsko.iRacingData.UnitTests/MockedHttpRequest.cs
- src/Aydsko.iRacingData.UnitTests/TestLogger.cs
- src/Aydsko.iRacingData.UnitTests/TrackScreenshotServiceTests.cs
- src/Aydsko.iRacingData/CompatibilitySuppressions.xml
- src/Aydsko.iRacingData/Converters/CsvStringConverter.cs
- src/Aydsko.iRacingData/Converters/DateOnlyConverter.cs
- src/Aydsko.iRacingData/Converters/DateTimeConverter.cs
- src/Aydsko.iRacingData/Converters/ServiceStatusHistoryItemConverter.cs
- src/Aydsko.iRacingData/Converters/StatusTimeStampConverter.cs
- src/Aydsko.iRacingData/Converters/TenThousandthSecondDurationConverter.cs
- src/Aydsko.iRacingData/Converters/UriConverter.cs
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/IDataClient.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
- src/Aydsko.iRacingData/ServicesExtensions.cs
- src/Aydsko.iRacingData/Tracks/Track.cs
- src/Aydsko.iRacingData/Tracks/TrackScreenshotService.cs
Move the implementation of the track screen shot URI generation to the main "IDataClient" interface so that it is easier to discover for users.
> Make Track Screen Shot URI Generation More Discoverable

- src/Aydsko.iRacingData/Leagues/Session.cs
- src/Aydsko.iRacingData/Leagues/SessionStatus.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
The "Status" field of the League Session as a fixed set of values. Update it to hold an enumeration to make those values more meaningful.
Fixes #182
> Implement "SessionStatus" Enumeration

- src/Aydsko.iRacingData/Results/Result.cs
> add missing car_class_name & car_class_short_name

- src/Aydsko.iRacingData.IntegrationTests/BaseIntegrationFixture.cs
- src/Aydsko.iRacingData.IntegrationTests/Logins/LoginTests.cs
- src/Aydsko.iRacingData.UnitTests/LoginViaOptionsTests.cs
- src/Aydsko.iRacingData/Common/ErrorResponse.cs
- src/Aydsko.iRacingData/CompatibilitySuppressions.xml
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/Exceptions/iRacingUnauthorizedResponseException.cs
- src/Aydsko.iRacingData/LoggingExtensions.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
If a "RestoreCookies" method is supplied and the cookies returned include any which apply to our base URL, then consider the client already authenticated so it doesn't have to call the login endpoint again.
Fixes #186
> Consider Client Logged In Cookies are Restored

- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/IDataClient.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
Open the "DataClient" implementation class up for extension via inheritance.
> Make "DataClient" Class "public"

- src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs
- src/Aydsko.iRacingData.UnitTests/CookiePersistenceTests.cs
- src/Aydsko.iRacingData.UnitTests/DataClientTrackAssetScreenshotUrisTests.cs
- src/Aydsko.iRacingData.UnitTests/LoginViaOptionsTests.cs
- src/Aydsko.iRacingData.UnitTests/TrackScreenshotServiceTests.cs
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
It is possible on a particular DataClient instance to call multiple methods and have each method trigger the authentication process. This leads to the login calls being made multiple times, wasting API calls.
This change places a lock such that the login process will be called once regardless of how many methods attempt to access it at the same time.
Fixes: #185
> Implement Locking for Authentication

- .github/workflows/ci.yml
- src/Aydsko.iRacingData/Aydsko.iRacingData.csproj
Update from "set-output" which is deprecated to the "GITHUB_OUTPUT" environment file.
> Set Output Params Correctly

- src/Aydsko.iRacingData.UnitTests/CookiePersistenceTests.cs
- src/Aydsko.iRacingData/DataClient.cs
Previously the code only checked the cookie container for relevant cookies if the "RestoreCookies" delegate was configured. This means that if the cookie container was populated some other way then the login process would be called again.
Move the check for cookies which might be existing, valid authentication outside the check for "RestoreCookies" delegate to take advantage of any data the collection already contains.
Fixes: #200
> Use Cookies Even Without "RestoreCookies"

- src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs
- src/Aydsko.iRacingData.UnitTests/Responses/GetSpectatorSubsessionDetailsSuccessfulAsync/1.json
- src/Aydsko.iRacingData.UnitTests/Responses/GetSpectatorSubsessionDetailsSuccessfulAsync/2.json
- src/Aydsko.iRacingData/CompatibilitySuppressions.xml
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/IDataClient.cs
- src/Aydsko.iRacingData/Series/SpectatorDetails.cs
- src/Aydsko.iRacingData/Series/SpectatorSubsessionDetail.cs
> Implement Spectator Subsession Details Retrieval

- src/Aydsko.iRacingData.UnitTests/LoginViaOptionsTests.cs
- src/Aydsko.iRacingData/DataClient.cs
This one bit me this week so I thought I'd put together a quick patch ... worst comes to worst it might be a jumping off point.
* Added a filter that excludes expired cookies when checking for active iracing cookies. 
* Added a unit test that checks that the expired cookies 
Sorry for the formatting changes, I tried to get my settings as close to yours as I could, looks like i failed.
> [fix] 213 - Library Considers Itself "Logged In" Despite Authentication Exception

- src/Aydsko.iRacingData/Series/WeatherSummary.cs
Change because the current calendar contains precipitation chances with a decimal value and this cannot be deserialised
> Change precipitation chance to decimal

- src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs
- src/Aydsko.iRacingData.UnitTests/MockedHttpMessageHandler.cs
- src/Aydsko.iRacingData.UnitTests/Responses/ResponseUnauthorizedLegacyRequired/0.json
- src/Aydsko.iRacingData/Common/ErrorResponse.cs
- src/Aydsko.iRacingData/CompatibilitySuppressions.xml
- src/Aydsko.iRacingData/DataClient.cs
- src/Aydsko.iRacingData/Exceptions/iRacingLoginFailedException.cs
- src/Aydsko.iRacingData/Package Release Notes.txt
iRacing will require a separate setting to turn off multi-factor authentication after it is introduced, so that simple username and password authentication can continue before they start enabling people to register OAuth applications.
> Handle the "Legacy Authentication" Setting
