src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberYearlyStatisticsSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberYearlyStatisticsSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberYearlyStatisticsSuccessfulAsync/2.json, src/Aydsko.iRacingData/IRacingDataClient.cs, src/Aydsko.iRacingData/Stats/MemberYearlyStatistics.cs
Implement the endpoint to get yearly statistics for the currently authenticated member.
Fixes #5
=> Implement "member/yearly" Endpoint

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberDivisionSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberDivisionSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberDivisionSuccessfulAsync/2.json, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/Results/SeasonResults.cs, src/Aydsko.iRacingData/Results/SessionInfo.cs, src/Aydsko.iRacingData/Results/SubSessionResult.cs, src/Aydsko.iRacingData/Stats/MemberDivision.cs
=> Implement "stats/member_division" Endpoint

.github/workflows/build.yml, src/Aydsko.iRacingData/Aydsko.iRacingData.csproj, src/Directory.Build.props, src/iRacing Data API.sln
Collect the code coverage output and report it as a PR comment.
=> Implement Code Coverage

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetSubsessionEventLogSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetSubsessionEventLogSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetSubsessionEventLogSuccessfulAsync/2.json, src/Aydsko.iRacingData.UnitTests/Responses/GetSubsessionEventLogSuccessfulAsync/3.json, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Results/SubsessionEventLogHeader.cs, src/Aydsko.iRacingData/Results/SubsessionEventLogItem.cs, src/Aydsko.iRacingData/Results/SubsessionLapHeader.cs
Create an implementation for the "results/event_log" endpoint along with a test.
Fixes: #27
=> Implement "results/event_log" Endpoint

src/Aydsko.iRacingData.UnitTests/ServicesTests.cs, src/Aydsko.iRacingData/ServicesExtensions.cs, src/Aydsko.iRacingData/iRacingDataClientOptions.cs
Includes options for setting a "product name" and a "version" to be used in the "User-Agent" header.
Fixes: #38
=> Add Product Name & Version Config for User Agent

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonTimeTrialResultsSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonTimeTrialResultsSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonTimeTrialResultsSuccessfulAsync/2.json, src/Aydsko.iRacingData.UnitTests/Responses/GetSeasonTimeTrialResultsSuccessfulAsync/3.json, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Stats/SeasonTimeTrialResult.cs, src/Aydsko.iRacingData/Stats/SeasonTimeTrialResultsHeader.cs
Implement the "/stats/season_tt_results" endpoint.
Fixes: #25
=> Implement Season Time Trial Results

README.md, src/Aydsko.iRacingData.UnitTests/LoginViaOptionsTests.cs, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/Package README.md, src/Aydsko.iRacingData/Package Release Notes.txt, src/Aydsko.iRacingData/iRacingDataClientOptions.cs
Starting in 2022 Season 3 there will be an updated requirement for how the username and password are presented. These changes allow a user of the library to enable this updated algorithm with a flag.
Fixes: #55
=> Implement Updated Login Algorithm

.github/workflows/build.yml
The code coverage publish doesn't work with pull requests due to permission issues. I don't look at it anyway, so just remove it.
=> Remove Code Coverage Step

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetSeriesSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetSeriesSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetSeriesSuccessfulAsync/2.json, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Series/AllowedLicenses.cs, src/Aydsko.iRacingData/Series/SeriesDetail.cs
Implement the `/data/series/get` endpoint.
=> Implement Get Series Endpoint

src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs
Added a customerId parameter to GetMemberRecentRacesAsync allowing customerId to be optionally supplied
=> Add customerId to GetMemberRecentRacesAsync

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/SearchLeagueDirectorySuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/SearchLeagueDirectorySuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/SearchLeagueDirectorySuccessfulAsync/2.json, src/Aydsko.iRacingData/Common/ResultOrderDirection.cs, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/Extensions.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Leagues/LeagueDirectoryResultItem.cs, src/Aydsko.iRacingData/Leagues/LeagueDirectoryResultPage.cs, src/Aydsko.iRacingData/Leagues/SearchLeagueDirectoryParameters.cs, src/Aydsko.iRacingData/Leagues/SearchLeagueOrderByField.cs
Implement the ability to search the league directory.
Fixes: #62
=> Add League Directory Search

src/Aydsko.iRacingData/DataClient.cs
This commit addresses the issue found in #105 for all other methods with chunkData requests.
=> add count check to all chunkData requests

README.md, src/Aydsko.iRacingData.UnitTests/Responses/GetLeagueMembershipAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetLeagueMembershipAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetLeagueMembershipAsync/2.json, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Leagues/LeagueMembership.cs
Trying to solve https://github.com/AdrianJSClark/aydsko-iracingdata/issues/97
=> Adds get league membership async

src/Aydsko.iRacingData.UnitTests/Responses/GetLeagueSeasonsAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetLeagueSeasonsAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetLeagueSeasonsAsync/2.json, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Leagues/Car.cs, src/Aydsko.iRacingData/Leagues/CarClass.cs, src/Aydsko.iRacingData/Leagues/CarInClass.cs, src/Aydsko.iRacingData/Leagues/LeagueSeasons.cs, src/Aydsko.iRacingData/Leagues/Season.cs
closes: https://github.com/AdrianJSClark/aydsko-iracingdata/issues/63
=> Implements `/data/league/seasons` endpoint

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/SearchDriversSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/SearchDriversSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/SearchDriversSuccessfulAsync/2.json, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Lookups/DriverSearchResult.cs, src/Aydsko.iRacingData/Package Release Notes.txt
=> Add Driver Search Support

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetRaceGuideSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetRaceGuideSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetRaceGuideSuccessfulAsync/2.json, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Package Release Notes.txt, src/Aydsko.iRacingData/Series/RaceGuideResults.cs, src/Aydsko.iRacingData/Series/RaceGuideSession.cs
=> Implement Race Guide Endpoint

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetBestLapStatisticsSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetBestLapStatisticsSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetBestLapStatisticsSuccessfulAsync/2.json, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Member/CarsDriven.cs, src/Aydsko.iRacingData/Member/MemberBest.cs, src/Aydsko.iRacingData/Member/MemberBests.cs, src/Aydsko.iRacingData/Package Release Notes.txt
=> Create Member Bests Endpoint

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetHostedSessionsCombinedSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetHostedSessionsCombinedSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetHostedSessionsCombinedSuccessfulAsync/2.json, src/Aydsko.iRacingData.UnitTests/Responses/GetHostedSessionsSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetHostedSessionsSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetHostedSessionsSuccessfulAsync/2.json, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/Hosted/CombinedSessionsResult.cs, src/Aydsko.iRacingData/Hosted/HostedSessionsResult.cs, src/Aydsko.iRacingData/IDataClient.cs
Add the hosted sessions & hosted combined sessions endpoints.
Somehow the implementation of the hosted combined wasn't completed in #109 and the shell of the method removed in a later commit. That is fixed here.
Fixes: #99, #98
=> Implement Sessions List Methods

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetTeamSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetTeamSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetTeamSuccessfulAsync/2.json, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Member/TeamInfo.cs, src/Aydsko.iRacingData/Member/TeamMember.cs, src/Aydsko.iRacingData/Package Release Notes.txt
=> Implement Team Data Retrieval

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetLeaguePointsSystemsSuccessfulAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetLeaguePointsSystemsSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetLeaguePointsSystemsSuccessfulAsync/2.json, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Leagues/LeagePointsSystems.cs, src/Aydsko.iRacingData/Leagues/PointsSystem.cs, src/Aydsko.iRacingData/Package Release Notes.txt
=> League Points Systems Endpoint

.github/workflows/ci.yml, .github/workflows/create-release.yml
Additional minor fixes to the reworked build files.
=> Rework Builds

.github/workflows/ci.yml, .github/workflows/create-release.yml
Ensure .NET SDK doesn't print unnecessary information to the output.
=> .NET SDK Environment Variables

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberParticipationCreditsSucceedsAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberParticipationCreditsSucceedsAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetMemberParticipationCreditsSucceedsAsync/2.json, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Member/ParticipationCredits.cs, src/Aydsko.iRacingData/Package Release Notes.txt
=> Implement the "Participation Credits" Endpoint

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData/Package Release Notes.txt, src/Aydsko.iRacingData/Series/PastSeriesDetail.cs
Include the full URI to the series logo via the "LogoUri" field.
=> Specify the Full Path for Series Logo Field

src/Aydsko.iRacingData/DataClient.cs
During an iRacing maintenance period an attempt to authenticate initially will fail with a "503 - Service Unavailable" HTTP error. This wasn't properly handled in the login method, as it would attempt to deserialize a JSON payload, when the error contained a HTML body
Assume when we see 503 that the service is in maintenance. For all other failures, return the generic login failed exception.
=> Improve Maintenance Period Handling

src/Aydsko.iRacingData/Aydsko.iRacingData.csproj, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Package Release Notes.txt, src/Aydsko.iRacingData/Results/DriverResult.cs, src/Aydsko.iRacingData/Results/Result.cs, src/Aydsko.iRacingData/Searches/OfficialSearchParameters.cs, src/Aydsko.iRacingData/iRacingDataClientOptions.cs
Generate documentation from the documentation comments that are included in the source. The resulting ".xml" files will be included in the NuGet package.
Make corrections to the documentation comments based on the issues raised by the documentation system.
Fixes #151
=> Ensure Documentation is Generated & Included in the Package

src/Aydsko.iRacingData/Aydsko.iRacingData.csproj, src/Aydsko.iRacingData/Package Release Notes.txt
=> Add Package Tags

src/Aydsko.iRacingData/Aydsko.iRacingData.csproj
=> Include Package Project URL

README.md, src/Aydsko.iRacingData.IntegrationTests/Aydsko.iRacingData.IntegrationTests.csproj, src/Aydsko.iRacingData.IntegrationTests/CachingIntegrationFixture.cs, src/Aydsko.iRacingData.IntegrationTests/Lookups/CachingLookupTests.cs, src/Aydsko.iRacingData.IntegrationTests/Member/CachingMemberInfoTest.cs, src/Aydsko.iRacingData.IntegrationTests/Results/CachingResultsGetTest.cs, src/Aydsko.iRacingData.IntegrationTests/Results/CachingResultsSearchSeriesTest.cs, src/Aydsko.iRacingData.IntegrationTests/Tracks/CachingGetTracksTests.cs, src/Aydsko.iRacingData.UnitTests/TestLogger.cs, src/Aydsko.iRacingData/Aydsko.iRacingData.csproj, src/Aydsko.iRacingData/CachingDataClient.cs, src/Aydsko.iRacingData/Common/IChunkInfoResultHeader.cs, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/Package README.md, src/Aydsko.iRacingData/Package Release Notes.txt, src/Aydsko.iRacingData/Searches/HostedResultsHeader.cs, src/Aydsko.iRacingData/Searches/OfficialSearchResultHeader.cs
Implement caching of the search results.
Fixes #165
=> Cache the Search Results

.github/workflows/_build.yml, .github/workflows/ci.yml, .github/workflows/create-release.yml, .github/workflows/publish-release.yml
Publishing of the documentation site along with the packages wasn't working. This should resolve it.
=> Fix Documentation Publish

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/GetCustomerLeagueSessionsAsync/0.json, src/Aydsko.iRacingData.UnitTests/Responses/GetCustomerLeagueSessionsAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/GetCustomerLeagueSessionsAsync/2.json, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Leagues/CustomerLeagueSession.cs, src/Aydsko.iRacingData/Leagues/CustomerLeagueSessionWeather.cs, src/Aydsko.iRacingData/Leagues/CustomerLeagueSessions.cs
This is for https://github.com/AdrianJSClark/aydsko-iracingdata/issues/70
This should work (worked on a outdated main), but I'm getting the following errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CP0006	Cannot add interface member 'Aydsko.iRacingData.IDataClient.GetCustomerLeagueSessionsAsync(bool, System.Nullable<int>, System.Threading.CancellationToken)' to lib/net6.0/Aydsko.iRacingData.dll because it does not exist on [Baseline] lib/net6.0/Aydsko.iRacingData.dll	Aydsko.iRacingData	C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ApiCompat.ValidatePackage.targets	37	
Error	CP0006	Cannot add interface member 'Aydsko.iRacingData.IDataClient.GetCustomerLeagueSessionsAsync(bool, System.Nullable<int>, …
```
=> Implements /data/league/cust_league_sessions

src/Aydsko.iRacingData.IntegrationTests/Member/CachingMemberInfoTest.cs, src/Aydsko.iRacingData.IntegrationTests/Member/MemberInfoTest.cs, src/Aydsko.iRacingData.IntegrationTests/Member/Security.cs, src/Aydsko.iRacingData/Member/MemberInfo.cs, src/Aydsko.iRacingData/Package Release Notes.txt
Updates the integration tests to work with the new security changes in 2023 Season 3 Patch 1.
=> Handle 2023 Season 3 Patch 1 Security Change

src/Aydsko.iRacingData.IntegrationTests/Stats/DriverStatisticsByCategoryCsvTests.cs, src/Aydsko.iRacingData/Common/LinkResult.cs, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Package Release Notes.txt, src/Aydsko.iRacingData/Stats/DriverStatisticsCsvFile.cs
Implement a method to retrieve the CSV with driver statistics.
Fixes: #205
=> Driver Statistics CSV Retrieval

src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Responses/ListHostedSessionsCombinedSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/ListHostedSessionsCombinedSuccessfulAsync/2.json, src/Aydsko.iRacingData.UnitTests/Responses/ListHostedSessionsSuccessfulAsync/1.json, src/Aydsko.iRacingData.UnitTests/Responses/ListHostedSessionsSuccessfulAsync/2.json, src/Aydsko.iRacingData/Aydsko.iRacingData.csproj, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/Hosted/Car.cs, src/Aydsko.iRacingData/Package Release Notes.txt, src/Aydsko.iRacingData/Series/CarRestrictions.cs
=> Resolve Data Type Error for Fuel Percentage

src/Aydsko.iRacingData.IntegrationTests/Aydsko.iRacingData.IntegrationTests.csproj, src/Aydsko.iRacingData.UnitTests/Aydsko.iRacingData.UnitTests.csproj, src/Aydsko.iRacingData.UnitTests/CapturedResponseValidationTests.cs, src/Aydsko.iRacingData.UnitTests/Converters/UtcOffsetToTimeSpanArrayConverterTests.cs, src/Aydsko.iRacingData.UnitTests/UrlExtensionsTests.cs, src/Aydsko.iRacingData/Aydsko.iRacingData.csproj, src/Aydsko.iRacingData/Cars/CarAssetDetail.cs, src/Aydsko.iRacingData/Cars/CarInfo.cs, src/Aydsko.iRacingData/Cars/CarRule.cs, src/Aydsko.iRacingData/Common/CarClass.cs, src/Aydsko.iRacingData/Common/CarsInClass.cs, src/Aydsko.iRacingData/CompatibilitySuppressions.xml, src/Aydsko.iRacingData/Converters/OneDecimalPointValueConverter.cs, src/Aydsko.iRacingData/Converters/TrackConfigNameNaConverter.cs, src/Aydsko.iRacingData/Converters/TwoDecimalPointsValueConverter.cs, src/Aydsko.iRacingData/DataClient.cs, src/Aydsko.iRacingData/Exceptions/iRacingUnauthorizedResponseException.cs, src/Aydsko.iRacingData/Extensions.cs, src/Aydsko.iRacingData/IDataClient.cs, src/Aydsko.iRacingData/Leagues/LeagePointsSystems.cs, src/Aydsko.iRacingData/Leagues/LeaguePointsSystems.cs, src/Aydsko.iRacingData/Leagues/PointsSystem.cs, src/Aydsko.iRacingData/Leagues/SeasonStandings.cs, src/Aydsko.iRacingData/Leagues/SeasonStandingsDriverStandings.cs, src/Aydsko.iRacingData/Leagues/Session.cs, src/Aydsko.iRacingData/Package Release Notes.txt, src/Aydsko.iRacingData/Series/ForecastOptions.cs, src/Aydsko.iRacingData/Series/Seasons.cs
Fix compiler warnings and some spelling errors.
=> Resolution of Compiler Warnings
